name: Cache Demo Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache dependencies
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/pip
          key: cache-11c4f44

      # Prime cache step
      - name: prime-cache-11c4f44
        run: |
          if [ -n "${{ steps.cache-deps.outputs.cache-hit }}" ]; then
            echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
          else
            echo "Cache miss: ${{ steps.cache-deps.outputs.cache-hit }}"
          fi

      # Install dependencies (example)
      - name: Install dependencies
        run: |
          # Node.js example
          npm install
          # Python example
          pip install -r requirements.txt

      # Example build/test step
      - name: Run tests
        run: echo "Running tests..."
